// Regenerates src/geo/flagAssets.generated.ts from the flag-icons package.
// Run with: node scripts/generate-flags.mjs
//
// Add a country by adding an entry to CODES below: the flag-icons 2-letter
// code (filename in node_modules/flag-icons/flags/4x3/) mapped to the
// world-atlas numeric ISO-3166-1 id (used by src/geo/globe.ts).
import { readFileSync, writeFileSync } from "fs";
import path from "path";

const CODES = {
  us: "840", // USA
  de: "276", // Germany
  cn: "156", // China
  jp: "392", // Japan
  gb: "826", // United Kingdom
  fr: "250", // France
  kr: "410", // South Korea
  in: "356", // India
  ch: "756", // Switzerland
  ru: "643", // Russia
  sa: "682", // Saudi Arabia
  br: "076", // Brazil
  ca: "124", // Canada
  tw: "158", // Taiwan
  it: "380", // Italy
  es: "724", // Spain
  nl: "528", // Netherlands
  au: "036", // Australia
  mx: "484", // Mexico
  ae: "784", // United Arab Emirates
  ir: "364", // Iran
  il: "376", // Israel
  ua: "804", // Ukraine
  tr: "792", // Turkey
};

let out = "// Auto-generated by scripts/generate-flags.mjs - do not edit by hand.\n";
out += "export type FlagAsset = { viewBox: string; inner: string };\n";
out += "export const FLAG_ASSETS_BY_ISO: Record<string, FlagAsset> = {\n";

for (const [a2, iso] of Object.entries(CODES)) {
  const raw = readFileSync(path.join("node_modules/flag-icons/flags/4x3", `${a2}.svg`), "utf8");
  const viewBox = /viewBox="([^"]+)"/.exec(raw)?.[1] ?? "0 0 640 480";
  const inner = raw.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
  out += `  "${iso}": { viewBox: ${JSON.stringify(viewBox)}, inner: ${JSON.stringify(inner)} },\n`;
}

out += "};\n";

writeFileSync("src/geo/flagAssets.generated.ts", out);
console.log(`Wrote src/geo/flagAssets.generated.ts (${Object.keys(CODES).length} flags)`);
